[project]
name = "unnamed"
version = "0.1.0"
vhdl_std = "2008"

[build]
sources = [
    "src/**/*.vhd",
    "src/**/*.vhdl",
]
vhdl_std = "2008"

[simulation]
duration_ns = 1000
wave_format = "vcd"

[devices]
target = ""

[timing]
constraints = []
